// Code generated by protoc-gen-go. DO NOT EDIT.
// source: heartbeat.proto

package cspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HeartbeatToS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatToS) Reset()         { *m = HeartbeatToS{} }
func (m *HeartbeatToS) String() string { return proto.CompactTextString(m) }
func (*HeartbeatToS) ProtoMessage()    {}
func (*HeartbeatToS) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{0}
}

func (m *HeartbeatToS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatToS.Unmarshal(m, b)
}
func (m *HeartbeatToS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatToS.Marshal(b, m, deterministic)
}
func (m *HeartbeatToS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatToS.Merge(m, src)
}
func (m *HeartbeatToS) XXX_Size() int {
	return xxx_messageInfo_HeartbeatToS.Size(m)
}
func (m *HeartbeatToS) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatToS.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatToS proto.InternalMessageInfo

type HeartbeatToC struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatToC) Reset()         { *m = HeartbeatToC{} }
func (m *HeartbeatToC) String() string { return proto.CompactTextString(m) }
func (*HeartbeatToC) ProtoMessage()    {}
func (*HeartbeatToC) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{1}
}

func (m *HeartbeatToC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatToC.Unmarshal(m, b)
}
func (m *HeartbeatToC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatToC.Marshal(b, m, deterministic)
}
func (m *HeartbeatToC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatToC.Merge(m, src)
}
func (m *HeartbeatToC) XXX_Size() int {
	return xxx_messageInfo_HeartbeatToC.Size(m)
}
func (m *HeartbeatToC) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatToC.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatToC proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HeartbeatToS)(nil), "heartbeatToS")
	proto.RegisterType((*HeartbeatToC)(nil), "heartbeatToC")
}

func init() { proto.RegisterFile("heartbeat.proto", fileDescriptor_3c667767fb9826a9) }

var fileDescriptor_3c667767fb9826a9 = []byte{
	// 79 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x48, 0x4d, 0x2c,
	0x2a, 0x49, 0x4a, 0x4d, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xe2, 0xe3, 0xe2, 0x81,
	0x0b, 0x85, 0xe4, 0x07, 0xa3, 0xf1, 0x9d, 0x9d, 0xc4, 0xa2, 0x44, 0xd2, 0x8b, 0xd3, 0xf4, 0xc1,
	0x8a, 0x93, 0xf3, 0x73, 0xf4, 0x93, 0x8b, 0xf5, 0x93, 0x8b, 0x0b, 0x92, 0x92, 0xd8, 0xc0, 0x22,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xf8, 0x87, 0xe7, 0x51, 0x00, 0x00, 0x00,
}
